# Generated by Django 4.2.5 on 2023-11-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='shampoo',
            field=models.BooleanField(default=False),
        ),
    ]
