# Generated by Django 4.2.5 on 2023-11-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_produto_shampoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='condicionador',
            field=models.BooleanField(default=False),
        ),
    ]
